### ISSUE TITLE
Compilation error with  less-grails-asset-pipeline

### ISSUE THREAD

**Issue by demon101** [select2/select2-bootstrap-theme#21]
With less-grails-asset-pipeline plugin https://github.com/bertramdev/less-grails-asset-pipeline I get following sintax error during compilation: 

2015-08-07 17:03:01,065 [http-bio-8070-exec-2] ERROR [/manga].[default]  - Servlet.service() for servlet [default] in context with path [/manga] threw exception [Filter execution threw an exception] with root cause
com.github.sommeri.less4j.Less4jException: Could not compile less. 2 error(s) occurred:
ERROR 183:12 mismatched character 'h' expecting '>'
 182: 
 183:         &--highlighted[aria-selected] {
 184:             background-color: @dropdown-link-active-bg;

ERROR 332:12 mismatched character 'a' expecting '>'
 331:         margin-top: -1px;
 332:         &--above {
 333:             margin-top: 1px;

```
at com.github.sommeri.less4j.core.ThreadUnsafeLessCompiler.compile(ThreadUnsafeLessCompiler.java:78)
at com.github.sommeri.less4j.LessCompiler$compile.call(Unknown Source)
at asset.pipeline.less.Less4jProcessor.process(Less4jProcessor.groovy:27)
at asset.pipeline.Processor$process.call(Unknown Source)
at asset.pipeline.less.LessAssetFile.processedStream(LessAssetFile.groovy:42)
at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:295)
at asset.pipeline.DirectiveProcessor$fileContents$2.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at asset.pipeline.DirectiveProcessor$fileContents$2.call(Unknown Source)
at asset.pipeline.AssetPipeline.serveUncompiledAsset(AssetPipeline.groovy:65)
at asset.pipeline.AssetPipeline$serveUncompiledAsset$1.call(Unknown Source)
at asset.pipeline.grails.AssetPipelineFilter.doFilter(AssetPipelineFilter.groovy:98)
```

**Comment by fk** [comment]
Well … first let me state that I'm not super familiar with Less.

What I can vouch for is that compiling the Less version of select2-bootstrap-theme to CSS via the [command line](http://lesscss.org/#using-less-command-line-usage) works fine – you can try so yourself from within the root folder of the repository by issuing `lessc --verbose src/build.less tmp/test.css`.

A quick look at the README of "LESS Grails Asset Pipeline" makes me wonder if things might work for you if you use the standard Less compiler instead of the [default less4j](https://github.com/bertramdev/less-grails-asset-pipeline#less4j-support) compiler?

**Comment by fk** [comment]
@demon101 Any news on this?

**Comment by demon101** [comment]
@fk I have changed version of asset pipeline and it works

**Comment by fk** [comment]
@demon101 Thanks for the quick reply, good to hear things are working for you now!
